# Configure what Git(hub) branches get tested
branches:
  only:
    - master
    - server
    - client

# Configure Node.jS environment
language: node_js
node_js:
  - "stable"
install:
  - npm install
cache: npm ci
services:
  - mongodb
before_script:
  - mongo Todos-local --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
env:
  global:
    - DBNAME_LOCAL=Todo-local
    - NODE_ENV=testing

# Staging for jobs
jobs:
  include:
    - stage: "Lint and test codebase"
      script: npm run lint
      script: npm run test