# NOTE CI Runs on Ubuntu
# Configure Node.jS environment
language: node_js
node_js:
  - "stable"
install:
  - npm install
  - cd "client" && npm install && cd "../"
cache: npm
services:
  - mongodb
before_script:
  - mongo Todos-local --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
env:
  global:
    - DBNAME_LOCAL=Todo-local
    - NODE_ENV=testing
    - MONGODB_URI_LOCAL=mongodb://http://127.0.0.1:27017

# Staging for jobs
jobs:
  include:
    - stage: "Unit test codebase"
      # type check code, ensures the code doesn't break before Heroku builds it
      script: npm run build -- --noEmit
      script: npm run coverage
