# NOTE CI Runs on Ubuntu
# Configure Node.jS environment
language: node_js
node_js:
  - "stable"
install:
  - npm install
cache: npm
services:
  - mongodb
before_script:
  - mongo Todos-local --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
env:
  global:
    - DBNAME_LOCAL=Todo-local
    - NODE_ENV=testing
    - MONGODB_URI_LOCAL=mongodb://http://127.0.0.1:27017

# Staging for jobs
jobs:
  include:
    - stage: "Unit test codebase"
      # Build serverside and clientside code, make sure it doesn't crash
      script: npm run build:client && npm run build:server
      script: npm run coverage
